### ISSUE TITLE
Migration from core `remind` plugin

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel-remind#1]
Was thinking about the transition from core's `remind` to this today, and more specifically considering the data migration path.

Reading the core plugin's ".db" file (actually TSV) is really easy with `csv.reader(..., delimiter='\t')`. I'm just curious if you have any thoughts about where the actual migration would go: Part of the `backend.setup()` routine, a separate conversion script for the bot owner to run manually, or somewhere else.

Actually _doing_ the migration is really simple, assuming the timestamp field this plugin saves is equivalent to the core plugin's. I think it should be. For best-effort timezone safety, knowing that the output of `time.gmtime(time.time())` is _specified_ to be in UTC, unlike `time.time()` by itself ([what core `remind` uses](https://github.com/sopel-irc/sopel/blob/f2712b1033e231b19383fbdf895bfef153e53e76/sopel/modules/remind.py#L116)), the migration can pass the core plugin's timestamps through `time.mktime(time.gmtime(original_timestamp))` to be Reasonably Sure™ that the final result will be in UTC.

Everything else is just more details, like if an automatic migration would rename the original file, or store a flag somewhere to skip migration after running it once, that kind of thing.

**Comment by Exirel** [comment]
And done!
